"""Publication figures for the Reasoning Budget Arena release candidate.

All numbers are read from the verified CSVs in ../data/ — no value is typed by
hand. Requires data/d-vs-c.csv (generated by scripts/validate_scores.py, or by
the lock-artifact validation step) and data/formal-{d,c}-objective.csv for the
delivery chart.

Outputs SVG + PNG into ../figures/.

Run:  python make_figures.py
"""
from __future__ import annotations

import csv
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

HERE = os.path.dirname(os.path.abspath(__file__))
RC = os.path.dirname(HERE)
DATA = os.path.abspath(os.path.join(RC, "data"))
FIG = os.path.abspath(os.path.join(RC, "figures"))
os.makedirs(FIG, exist_ok=True)

plt.rcParams.update({
    "font.size": 10, "axes.spines.top": False, "axes.spines.right": False,
    "figure.dpi": 150, "savefig.bbox": "tight",
})
C_D = "#9aa5b1"   # Formal D (native thinking, no reasoning budget)
C_C = "#2b6cb0"   # Formal C (+ hard reasoning budget 4096)

# display-name shortening (labels only; no numbers involved)
SHORT = {
    "RavenX-CyberAgent-35B-v5.1-Q4_K_M": "RavenX 35B",
    "Endy-Qwen3.6-CyberSec-35B-A3B-Q4_K_M": "Endy CyberSec 35B",
    "Gemma4-26B-A4B-QAT-Uncensored-HauhauCS-Balanced-Q4_K_M": "Gemma4 26B",
    "Ornith-1.5-35B-A3B-Abliterated-Q4_K_M": "Ornith 35B",
    "Nex-N2-mini-Q4_K_M": "Nex-N2-mini",
    "Qwen3.8-9B-abliterated-25-Q4_K_M": "Qwen3.8 9B",
}


def save(fig, name):
    fig.savefig(os.path.join(FIG, name + ".svg"))
    fig.savefig(os.path.join(FIG, name + ".png"))
    plt.close(fig)
    print("wrote figures/" + name + ".svg/.png")


def load_master():
    p = os.path.join(DATA, "d-vs-c.csv")
    if not os.path.exists(p):
        return None
    rows = list(csv.DictReader(open(p, encoding="utf-8-sig")))
    for r in rows:
        for k in ("d_general", "c_general", "d_cyber", "c_cyber", "d_overall",
                  "c_overall", "delta_general", "delta_cyber", "delta_overall"):
            r[k] = float(r[k])
        for k in ("d_rank", "c_rank", "rank_change"):
            r[k] = int(r[k])
    return rows


def grouped(rows, dk, ck, title, fname, ymax):
    rows = sorted(rows, key=lambda r: -r[ck])
    labels = [SHORT.get(r["model"], r["model"]) for r in rows]
    dv = [r[dk] for r in rows]
    cv = [r[ck] for r in rows]
    x = range(len(rows))
    fig, ax = plt.subplots(figsize=(7.0, 4.0))
    b1 = ax.bar([i - 0.2 for i in x], dv, width=0.4, color=C_D, label="Formal D (native thinking)")
    b2 = ax.bar([i + 0.2 for i in x], cv, width=0.4, color=C_C, label="Formal C (+ reasoning budget 4096)")
    for b in b1:
        ax.text(b.get_x() + b.get_width() / 2, b.get_height() + ymax * 0.012,
                f"{b.get_height():.1f}", ha="center", fontsize=8)
    for b in b2:
        ax.text(b.get_x() + b.get_width() / 2, b.get_height() + ymax * 0.012,
                f"{b.get_height():.1f}", ha="center", fontsize=8)
    ax.set_xticks(list(x))
    ax.set_xticklabels(labels, rotation=20, ha="right")
    ax.set_ylim(0, ymax)
    ax.set_ylabel("blind score")
    ax.set_title(title, fontsize=11)
    ax.legend(frameon=False, fontsize=9, loc="lower right")
    save(fig, fname)


def final_delivery():
    def count(path):
        n, tot = 0, 0
        for r in csv.DictReader(open(path, encoding="utf-8-sig")):
            tot += 1
            if r["has_final"] == "yes":
                n += 1
        return n, tot
    dn, dt = count(os.path.join(DATA, "formal-d-objective.csv"))
    cn, ct = count(os.path.join(DATA, "formal-c-objective.csv"))
    labels = ["Formal D\n(native thinking,\nno reasoning budget)",
              "Formal C\n(+ hard reasoning\nbudget 4096)"]
    vals = [dn, cn]
    fig, ax = plt.subplots(figsize=(5.2, 4.2))
    bars = ax.bar(labels, vals, width=0.55, color=[C_D, C_C])
    for b, v, t in zip(bars, vals, [dt, ct]):
        ax.text(b.get_x() + b.get_width() / 2, v + 3, f"{v}/{t}",
                ha="center", fontsize=13, fontweight="bold")
    ax.axhline(ct, color="#cccccc", lw=1, ls="--")
    ax.set_ylim(0, 210)
    ax.set_ylabel("non-empty final answers")
    ax.set_title("Final-answer delivery under the same frozen 32-question\n"
                 "benchmark and 8192-token context window", fontsize=11)
    ax.text(0.5, -0.24,
            f"Formal D: {dt - dn} empty finals. Formal C: {ct - cn} empty finals observed in this run.",
            transform=ax.transAxes, ha="center", fontsize=9, color="#444444")
    save(fig, "final-delivery")


def rank_slopegraph(rows):
    fig, ax = plt.subplots(figsize=(5.6, 4.2))
    for r in rows:
        xd, xc = 0, 1
        rd, rc_ = r["d_rank"], r["c_rank"]
        moved = r["rank_change"]
        color = "#2b6cb0" if moved > 0 else ("#9aa5b1" if moved == 0 else "#c05621")
        ax.plot([xd, xc], [rd, rc_], "-o", color=color, lw=1.8, markersize=7)
        ax.text(xd - 0.03, rd, f" {SHORT.get(r['model'], r['model'])} (#{rd})",
                ha="right", va="center", fontsize=8.5)
        ax.text(xc + 0.03, rc_, f"(#{rc_}) {SHORT.get(r['model'], r['model'])} ",
                ha="left", va="center", fontsize=8.5)
    ax.set_xticks([0, 1])
    ax.set_xticklabels(["Formal D\n(native thinking)", "Formal C\n(+ budget 4096)"])
    ax.set_ylim(6.6, 0.4)
    ax.set_yticks([1, 2, 3, 4, 5, 6])
    ax.set_ylabel("overall rank")
    ax.set_xlim(-0.85, 1.85)
    ax.set_title("Overall rank movement (6 models, blind scores /800)", fontsize=11)
    save(fig, "rank-change")


def delta_bar(rows):
    rows = sorted(rows, key=lambda r: -r["delta_overall"])
    labels = [SHORT.get(r["model"], r["model"]) for r in rows]
    vals = [r["delta_overall"] for r in rows]
    fig, ax = plt.subplots(figsize=(7.0, 3.8))
    bars = ax.barh(labels, vals, color=C_C, height=0.6)
    for b, v in zip(bars, vals):
        ax.text(v + 6, b.get_y() + b.get_height() / 2, f"+{v:.1f}", va="center", fontsize=9)
    ax.set_xlim(0, max(vals) * 1.18)
    ax.set_xlabel("overall score change, Formal D -> Formal C (points / 800)")
    ax.set_title("Every model scored higher under the reasoning-budget condition "
                 "(descriptive; one run, no replicates)", fontsize=10)
    ax.invert_yaxis()
    save(fig, "score-delta")


if __name__ == "__main__":
    final_delivery()
    rows = load_master()
    if rows is None:
        print("skipped score charts: data/d-vs-c.csv not present")
    else:
        grouped(rows, "d_overall", "c_overall", "Overall blind scores — /800", "overall-d-vs-c", 800)
        grouped(rows, "d_general", "c_general", "General division — /450", "general-d-vs-c", 450)
        grouped(rows, "d_cyber", "c_cyber", "Cyber division — /350", "cyber-d-vs-c", 350)
        rank_slopegraph(rows)
        delta_bar(rows)
